version: '3.8'

services:
  mariadb:
    build: .
    container_name: task-chat-mysql-container
    ports:
      - "33061:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: task_chat_db
      MYSQL_USER: task_local
      MYSQL_PASSWORD: 1234
    volumes:
      - ./seeding/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./seeding/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mariadb-data:
    driver: local
